import 'ui/styles/globals.css'

import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: { children: React.ReactNode }): JSX.Element {
  return (
    <html className={montserrat.className} lang='en'>
      <body>{children}</body>
    </html>
  )
}
